# Generated by Django 5.0.3 on 2024-05-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cover_image_url', models.URLField()),
                ('ratings', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
    ]
